#!/usr/bin/env python
"""The TEMPLATE PAGES, generated from the registry so a page cannot drift.

Writes ``docs/templates/index.md`` (the gallery), ``docs/templates/<name>.md``
(one page per registered template) and ``docs/modules.md`` (the wrappers). Every
fact comes from a declaration or from the committed run record beside the figures.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "contracts"))

__all__ = ["generate", "main", "render_index", "render_modules", "render_template"]

#: Where the pages and their figures live.
DOC_ROOT = REPO / "docs" / "templates"
#: The committed record of the run a page documents, written by the doc renderer.
RUN_RECORD = "run.json"
#: What every generated page says about itself, so nobody edits one by hand.
_BANNER = ("<!-- GENERATED by scripts/instruments/gen_template_docs.py. "
           "Edit the declaration, not this file. -->")
#: Figure suffixes, in the order a page reads: the stacked canvas, the animation
#: of the field the template declares, the still that field peaks at, the chart.
_FIGURE_ORDER = (".png", ".gif")


def _templates() -> dict[str, Any]:
    """Every registered engine template, by tool name -> its ``Workflow``."""
    import trid3nt_server.tools  # noqa: F401 - the import IS the registration
    from trid3nt_server.tools import TOOL_REGISTRY

    found = {name: getattr(entry.fn, "workflow", None)
             for name, entry in TOOL_REGISTRY.items()}
    return dict(sorted(
        (name, workflow) for name, workflow in found.items()
        if workflow is not None and getattr(workflow.plan_decl, "steering", None)))


def _question(name: str) -> str:
    """The template's one-line question, off the docstring the model routes on."""
    from trid3nt_server.tools import TOOL_REGISTRY

    doc = (TOOL_REGISTRY[name].fn.__doc__ or "").strip()
    return doc.splitlines()[0] if doc else name


def _runner_doc(runner: str) -> str:
    """One line about what a DATA row's producer is, off the producer itself."""
    from trid3nt_server.tools import TOOL_REGISTRY

    entry = TOOL_REGISTRY.get(runner)
    if entry is not None:
        doc = (entry.fn.__doc__ or "").strip()
        return doc.splitlines()[0] if doc else ""
    if "." not in runner:
        return ""
    module_path, _, attribute = runner.rpartition(".")
    try:
        from importlib import import_module

        doc = (getattr(import_module(module_path), attribute).__doc__ or "").strip()
    except Exception:  # noqa: BLE001 - an unresolvable producer documents as blank
        return ""
    return doc.splitlines()[0] if doc else ""


def _datum(runner: str) -> str:
    """The vertical datum the declared source states, or blank when it states none."""
    from trid3nt_server.tools.fetchers._router.registration import get_spec

    spec = get_spec(runner)
    return str(getattr(spec, "vertical_datum", "") or "") if spec else ""


def _cell(value: Any) -> str:
    """One table cell: pipes escaped, newlines flattened, empty rendered as a dash."""
    if value is None or value == "":
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _table(header: tuple[str, ...], rows: list[tuple]) -> list[str]:
    """A markdown table, or nothing at all when there are no rows."""
    if not rows:
        return []
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(_cell(cell) for cell in row) + " |" for row in rows]
    return out + [""]


def _record(name: str) -> dict:
    """The committed run record for a template, or ``{}`` when it has none."""
    path = DOC_ROOT / name / RUN_RECORD
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _figures(name: str) -> list[Path]:
    """This template's doc renders, in reading order, relative to the page."""
    folder = DOC_ROOT / name
    if not folder.is_dir():
        return []
    found = [p for p in folder.iterdir() if p.suffix.lower() in _FIGURE_ORDER]
    composite = [p for p in found if p.stem == name]
    animation = sorted(p for p in found if p.suffix.lower() == ".gif")
    still = sorted(p for p in found if "_frame" in p.stem)
    chart = sorted(p for p in found if "_chart" in p.stem)
    ordered = composite + animation + still + chart
    return ordered + sorted(set(found) - set(ordered))


def _caption(name: str, path: Path, record: dict) -> str:
    """What one figure shows, said in the page rather than left to the picture."""
    run = record.get("run_id", "")
    if path.stem == name:
        return f"Every layer the run published, stacked and framed on the result (run {run})"
    if path.suffix.lower() == ".gif":
        field = path.stem[len(name):].removeprefix("_animation").strip("_")
        return (f"The solve, frame by frame{f' - {field}' if field else ''} "
                f"(run {run})")
    if "_chart" in path.stem:
        return (f"{path.stem.split('_chart_', 1)[-1].replace('_', ' ')} - the chart "
                f"the run persisted (run {run})")
    return f"{path.stem[len(name):].strip('_').replace('_', ' ')} (run {run})"


def render_template(name: str, workflow: Any) -> str:
    """One template's page: its declaration, its proving run, its figures."""
    steering = workflow.plan_decl.steering
    stated = {key for part in (*steering.PARTS, steering) for key in part.ASSERTED}
    stated |= set(workflow.plan_decl.slots)
    record = _record(name)
    lines = [_BANNER, "", f"# `{name}`", "", _question(name), ""]

    lines += _table(("", ""), [
        ("module", f"`{steering.MODULE}` - {len(steering.CATALOG)} keywords in its "
                   f"dictionary, of which this template states {len(stated)}"),
        ("parts", ", ".join(f"`{part.__name__}`" for part in steering.PARTS) or "-"),
        ("solves", f"`{workflow.plan_decl.dispatch}`"),
        ("engine defaults", "every keyword this template does not state keeps the "
                            "engine's own default; `describe_keywords` names it "
                            "with that default, and `keywords={...}` sets it"),
    ])

    lines += ["## The data it consumes", ""]
    lines += _table(("row", "produced by", "what it is", "datum"), [
        (f"`{row.name}`",
         f"`{row.producer.runner}`" if row.producer else "supplied by the caller",
         _runner_doc(row.producer.runner) if row.producer else row.doc_line,
         _datum(row.producer.runner) if row.producer else "")
        for row in workflow.data])

    lines += ["## The sheet", "",
              "The values the template declares. `desc` is what the model reads "
              "when it fills one.", ""]
    lines += _table(("param", "door", "units", "default", "desc"), [
        (f"`{param.name}`", param.door,
         param.units or "",
         "optional" if param.optional else param.default,
         param.desc)
        for param in workflow.params])

    lines += ["## What it answers", ""]
    lines += _table(("field", "the proving run's value"), [
        (f"`{field}`", (record.get("answer") or {}).get(field, ""))
        for field in workflow.answer_fields])
    published = [row.get("name") for row in record.get("layers") or []]
    if published:
        lines += ["It publishes these layers onto the canvas:", ""]
        lines += [f"- {layer}" for layer in published] + [""]

    if not record:
        return "\n".join(lines + ["## The proving run", "",
                                  "None rendered yet.", ""]) + "\n"

    lines += ["## The proving run", "",
              f"Run `{record['run_id']}`, {record.get('recorded_at', '')}, "
              f"{record.get('wall_seconds', '?')} s, at commit "
              f"`{record.get('commit', '')}`.", ""]

    for figure in _figures(name):
        lines += [f"![{_caption(name, figure, record)}]({name}/{figure.name})", "",
                  f"*{_caption(name, figure, record)}*", ""]

    lines += ["### The sheet it filled", "",
              "Every slot the run resolved, with where the value came from. The "
              "engine's own defaults are folded: what is not here, the engine "
              "chose.", ""]
    lines += _table(("param", "value", "units", "basis", "provenance"), [
        (f"`{row.get('name')}`", row.get("value"), row.get("units") or "",
         row.get("basis"), row.get("note") or "")
        for row in record.get("sheet") or []])

    lines += ["### Reproduce", "", "```python", "from trid3nt_server.tools import "
              "TOOL_REGISTRY", "", f"await TOOL_REGISTRY[{name!r}].fn(",
              *[f"    {line}" for line in _wire_args(record)], ")", "```", "",
              f"That is the invocation this run came from; the figures above are "
              f"stamped with run `{record['run_id']}` and commit "
              f"`{record.get('commit', '')}`. The full argument record is "
              f"[`{name}/{RUN_RECORD}`]({name}/{RUN_RECORD}).", ""]
    return "\n".join(lines) + "\n"


def _wire_args(record: dict) -> list[str]:
    """The run's own user-supplied arguments, one keyword per line."""
    return [f"{key}={value!r}," for key, value in
            sorted((record.get("args") or {}).items())]


def render_index(templates: dict[str, Any]) -> str:
    """The gallery: one card per registered template."""
    lines = [_BANNER, "", "# Templates", "",
             f"{len(templates)} registered templates, one per question. A template "
             "declares raw engine keywords over a module wrapper; `fill` sets the "
             "sheet and `run` solves it. The wrappers are in "
             "[`../modules.md`](../modules.md).", ""]
    for name, workflow in templates.items():
        record = _record(name)
        thumbnail = DOC_ROOT / name / f"{name}.png"
        lines += [f"## [`{name}`]({name}.md)", ""]
        if thumbnail.is_file():
            lines += [f"[![{name}]({name}/{thumbnail.name})]({name}.md)", ""]
        lines += [_question(name), "",
                  f"Module `{workflow.plan_decl.steering.MODULE}`"
                  + (f", proving run `{record['run_id']}`." if record else "."), ""]
    return "\n".join(lines) + "\n"


def render_modules() -> str:
    """The wrappers page: what each module's surface is, and how to read it."""
    from trid3nt_server.workflows.telemac.modules import WRAPPERS

    lines = [_BANNER, "", "# Module wrappers", "",
             "One wrapper per TELEMAC module. A wrapper is the module's own "
             "dictionary, read at import: every keyword, its type, its choices and "
             "its engine default. A template states a few of them and leaves the "
             "rest to the engine.", "",
             "`describe_keywords(module=..., query=...)` is the read over any of "
             "these catalogs - it answers with the keyword, the engine's own help "
             "text, its choices and its default.", ""]
    lines += _table(("module", "keywords", "composites", "outputs"), [
        (f"`{module}`", len(wrapper.CATALOG),
         ", ".join(f"`{key}`" for key in sorted(wrapper.COMPOSITES)) or "-",
         ", ".join(f"`{key}`" for key in sorted(wrapper.OUTPUTS)) or "-")
        for module, wrapper in sorted(WRAPPERS.items())])
    lines += ["A COMPOSITE is one value standing for a keyword group, so the group "
              "cannot half-arrive. An OUTPUT binds a result file to the reader that "
              "publishes it.", ""]
    return "\n".join(lines) + "\n"


def generate() -> dict[str, str]:
    """Every generated page, by repo-relative path -> its content."""
    templates = _templates()
    pages = {f"docs/templates/{name}.md": render_template(name, workflow)
             for name, workflow in templates.items()}
    pages["docs/templates/index.md"] = render_index(templates)
    pages["docs/modules.md"] = render_modules()
    return pages


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", default=False,
                    help="fail when a page on disk is not what this would write")
    ns = ap.parse_args(argv)

    stale = []
    for relative, content in generate().items():
        path = REPO / relative
        if ns.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(relative)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if ns.check and stale:
        print("STALE (regenerate with scripts/instruments/gen_template_docs.py):")
        print("\n".join(f"  {name}" for name in stale))
        return 1
    print(json.dumps({"pages": sorted(generate())}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
