<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>synthdrv</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Driver.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Ras.Core"><HintPath>/dll/Ras.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Ras.Engine"><HintPath>/dll/Ras.Engine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Geospatial.Core"><HintPath>/dll/Geospatial.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Geospatial.GDALAssist"><HintPath>/dll/Geospatial.GDALAssist.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Utility.Core"><HintPath>/dll/Utility.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="H5Assist"><HintPath>/dll/H5Assist.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Geospatial.Vectors"><HintPath>/dll/Geospatial.Vectors.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
